"""Reemplazar total_transferencia_sistema por total_nequi y total_bancolombia en ArqueoCaja

Revision ID: 321ba1325e75
Revises: 9563942c1c5f
Create Date: 2026-04-04 15:23:58.704484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321ba1325e75'
down_revision = '9563942c1c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_nequi_sistema', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_bancolombia_sistema', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_transferencia_sistema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_transferencia_sistema', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('total_bancolombia_sistema')
        batch_op.drop_column('total_nequi_sistema')

    # ### end Alembic commands ###
