"""Add invoice image field

Revision ID: 53923cae79be
Revises: c7296b0e49c9
Create Date: 2026-04-05 15:51:51.697387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53923cae79be'
down_revision = 'c7296b0e49c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_invoices', schema=None) as batch_op:
        batch_op.drop_column('comprobante')

    # ### end Alembic commands ###
