"""Agregar modelos POS Terminal: ProductVariant, SalePayment, campos en Sale y SaleDetail

Revision ID: 9476fad5e6e5
Revises: 53923cae79be
Create Date: 2026-04-14 20:05:49.627639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9476fad5e6e5'
down_revision = '53923cae79be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('nombre_variante', sa.String(length=100), nullable=False),
    sa.Column('sku_variante', sa.String(length=50), nullable=True),
    sa.Column('cantidad_stock', sa.Integer(), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_sugerido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_sku_variante'), ['sku_variante'], unique=True)

    op.create_table('sale_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('es_externo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('nombre_externo', sa.String(length=200), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('utilidad', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=30), nullable=False))

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('utilidad')
        batch_op.drop_column('costo_total')

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('nombre_externo')
        batch_op.drop_column('es_externo')
        batch_op.drop_column('costo_unitario')
        batch_op.drop_column('variant_id')

    op.drop_table('sale_payments')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku_variante'))

    op.drop_table('product_variants')
    # ### end Alembic commands ###
