"""Agregar campo metodo_pago al modelo Expense

Revision ID: 9563942c1c5f
Revises: fa8a23da2051
Create Date: 2026-04-04 15:16:48.763750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9563942c1c5f'
down_revision = 'fa8a23da2051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
